source "https://rubygems.org"
gem 'csv'
gem 'base64'
gem 'logger'
gem 'bigdecimal'
gem "kramdown"
gem "kramdown-parser-gfm"
gem "rouge"
gem "jekyll"
gem "jekyll-paginate"
gem "jekyll-paginate-content"
gem "json"
